HOSTS:
  ubuntu-16-04:
    roles:
      - master
    platform: ubuntu-1604-amd64
    image: ubuntu:16.04
    hypervisor: docker
    docker_cmd: ["/sbin/init"]
    docker_container_name: ubuntu-1604-amd64
    docker_preserve_image: true
    docker_image_commands:
      - apt-get update
      - apt-get install -yq libssl-dev apt-transport-https
      - locale-gen en_US en_US.UTF-8
      - dpkg-reconfigure locales
